import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// Can't use shadcn ui components in RootLayout file, because this file is a server component and can't be changed by using "use client"
// Instead you can create a Client component with children props and use it in your Root Layout, example below
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <header className="bg-gray-800 text-white p-4">Header</header>
        <main>{children}</main>
        <footer className="bg-gray-800 text-white p-4 text-center">
          Footer
        </footer>
      </body>
    </html>
  );
}

// Client component
// 'use client'

// import { ThemeProvider } from 'acme-theme'
// import { AuthProvider } from 'acme-auth'

// export function Providers({ children }) {
//   return (
//     <ThemeProvider>
//       <AuthProvider>{children}</AuthProvider>
//     </ThemeProvider>
//   )
// }

// In layout.tsx
// import { Providers } from './providers'

// export default function RootLayout({ children }) {
//   return (
//     <html>
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   )
// }
